### ISSUE TITLE
Multiple Games at Once

### ISSUE THREAD

**Issue by Romulus10** [InsidiousMind/Gomoku#24]

**Comment by InsidiousMind** [comment]
Generalize start_subserver and what's passed to it in order to accomadate for multiple games/lobby.

Instead of starting two subservers, pass all the info of the two players which will play against each other, and init the threads with this information

when we implement a lobby, this would make it easier to manage.

**Comment by InsidiousMind** [comment]
Local variables now work, this means half the work for multiple games is done. All that's left is a function which manages how multiple players connect, which will include development of a lobby.

**Comment by InsidiousMind** [comment]
Multiple games work...Kind of. Need more testing. Game hangs on a win, not sure why maybe it's because I destroy the Mutex variable.

In any case it's extremely painful to test multiple games. Having 5 terminals open (server, 2 for one game, 2 for the other) is ridiculous. Trying to avoid using GDB at all costs, because that would be even worse

**Comment by InsidiousMind** [comment]
I'm sure there are still bugs in some use cases for multiple games, but for the most part they work.
