### ISSUE TITLE
Bus Error (core dumped)

### ISSUE THREAD

**Issue by Romulus10** [InsidiousMind/Gomoku#35]
On FreeBSD, some invalid input causes a core dump.

**Comment by InsidiousMind** [comment]
I'm thinking the client should parse the inpuit and make sure it's sanitized before it's passed to the server

In an ideal world, both the server and client should parse input in order to avoid a vulnerability on the server which would allow a client to single-handedly crash it (if the client is created by a third party for example)

but we're running out of time, and I doubt Bi would go so far as to test the server with a third-party client which doesn't sanitize input just to screw with us

**Comment by Romulus10** [comment]
I'll work on writing input sanitizing in to the client.

**Comment by Romulus10** [comment]
Sanitizing the input should have fixed this. Confirm?
